version: 1.20.1.{build}

environment:
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    GEN: "Visual Studio 15 2017"
    matrix:
      - ARCH: Win32
        CFG: Release
      - ARCH: x64
        CFG: Release

build_script:
    - cmake -B .\build -G "%GEN%" -A %ARCH% -DALSOFT_BUILD_ROUTER=ON -DALSOFT_REQUIRE_WINMM=ON -DALSOFT_REQUIRE_DSOUND=ON -DALSOFT_REQUIRE_WASAPI=ON -DALSOFT_EMBED_HRTF_DATA=YES -DCMAKE_BUILD_TYPE:STRING=Release -DFORCE_STATIC_VCRT:BOOL=ON
    - cmake --build .\build --config %CFG% --clean-first
